from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class HealthResponse(BaseModel):
    status: str = Field("ok", description="Server health status")

class ErrorResponse(BaseModel):
    error: str = Field(..., description="Error message description")
    detail: Optional[str] = Field(None, description="Additional error context")

class QueryRequest(BaseModel):
    query: str = Field(..., min_length=1, description="Search query string")
    top_k: int = Field(5, ge=1, le=20, description="Number of document chunks to retrieve")

class DocumentReference(BaseModel):
    title: str
    content: str
    metadata: Dict[str, Any]
    similarity_score: float

class QueryResponse(BaseModel):
    answer: str
    references: List[DocumentReference]

class DocumentUploadResponse(BaseModel):
    document_id: str
    filename: str
    status: str
    page_count: int
    total_chunks: int
    file_hash: str
    is_duplicate: bool = False

class DocumentMetadata(BaseModel):
    document_id: str
    filename: str
    stored_path: str
    upload_time: str
    page_count: int
    total_chunks: int
    file_size: int
    file_hash: str

class DocumentListResponse(BaseModel):
    documents: List[DocumentMetadata]
    total_count: int

class DeleteDocumentResponse(BaseModel):
    message: str
    document_id: str

class RetrieveRequest(BaseModel):
    query: str = Field(..., min_length=1, description="User search query")
    document_ids: Optional[List[str]] = Field(None, description="Optional list of document IDs to restrict search scope")
    top_k: Optional[int] = Field(None, ge=1, le=50, description="Number of top chunks to return")
    similarity_threshold: Optional[float] = Field(None, ge=0.0, le=1.0, description="Minimum similarity score threshold")

class ChunkSearchResult(BaseModel):
    document_id: str
    filename: str
    page: int
    chunk_id: str
    content: str
    similarity_score: float
    metadata: Dict[str, Any]

class RetrieveResponse(BaseModel):
    query: str
    total_found: int
    results: List[ChunkSearchResult]

class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, description="User question or chat message")
    conversation_id: Optional[str] = Field(None, description="Optional conversation ID for context tracking")
    document_ids: Optional[List[str]] = Field(None, description="Optional document IDs filter")

class SourceReference(BaseModel):
    document: str = Field(..., description="Filename of the source document")
    page: int = Field(..., description="1-indexed page number")
    content: str = Field(..., description="Excerpt text from the document chunk")
    score: float = Field(..., description="Relevance / similarity score")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="Grounded answer generated by the assistant")
    sources: List[SourceReference] = Field(default_factory=list, description="Authentic citations for retrieved context")
    conversation_id: str = Field(..., description="Conversation ID")
